# Generated by Django 2.2.4 on 2019-08-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('is_accepted', models.BooleanField(null=True)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('response_url', models.CharField(max_length=255)),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_request', to='slackbot.Match')),
            ],
        ),
    ]
