# Generated by Django 2.2.4 on 2019-08-16 00:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('response_url', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('cancelled', 'Cancelled')], default='pending', max_length=255)),
                ('block_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=255)),
                ('coffee_count', models.IntegerField(default=1)),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=255)),
                ('ts', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('is_accepted', models.BooleanField(null=True)),
                ('expiration', models.DateTimeField()),
                ('response_url', models.CharField(blank=True, max_length=255)),
                ('block_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('coffee_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='slackbot.CoffeeRequest')),
                ('initial_message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='slackbot.SlackMessage')),
            ],
        ),
        migrations.AddField(
            model_name='coffeerequest',
            name='initial_message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coffee_request', to='slackbot.SlackMessage'),
        ),
    ]
