# Generated by Django 2.2.4 on 2019-08-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeerequest',
            name='matches',
        ),
        migrations.AddField(
            model_name='match',
            name='coffee_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='slackbot.CoffeeRequest'),
        ),
    ]
