# Generated by Django 2.2.4 on 2020-04-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeerequest',
            name='command',
            field=models.CharField(choices=[('/coffee', 'Coffee'), ('/connect', 'Connect')], default='/coffee', max_length=255),
        ),
    ]
