# Generated by Django 2.2.4 on 2019-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0002_auto_20190814_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='response_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
