# Generated by Django 2.2.4 on 2019-08-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0003_match_response_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='block_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='response_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
