# Generated by Django 2.2.4 on 2019-08-14 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0004_auto_20190814_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeerequest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
