# Generated by Django 2.2.4 on 2019-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0005_coffeerequest_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('cancelled', 'Cancelled')], default='pending', max_length=255),
        ),
    ]
