# Generated by Django 2.2.4 on 2019-08-15 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0009_auto_20190814_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSlackMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=255)),
                ('ts', models.CharField(max_length=255)),
                ('match', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='slackbot.Match')),
            ],
        ),
    ]
