# Generated by Django 2.2.4 on 2019-08-14 22:30

from django.db import migrations


def unassign_all_investors_from_representatives(apps, schema_editor):
    Recommendation = apps.get_model("slackbot", "Recommendation")

    Recommendation.objects.create(name="Gasoline Alley", link="https://goo.gl/maps/M93HjGqrtreaV3om7", specialty="Iced Americano")
    Recommendation.objects.create(name="La Colombe", link="https://goo.gl/maps/yxnjUorEvxrzcKhb9", specialty="Black and Tan")
    Recommendation.objects.create(name="Maman", link="https://goo.gl/maps/vj1mjmbxqV1TXZSr6", specialty="Maman's 'Famous' Nutty Chocolate Chunk Cookie")
    Recommendation.objects.create(name="Maman", link="https://goo.gl/maps/vj1mjmbxqV1TXZSr6", specialty="Honey Lavendar Latte")
    Recommendation.objects.create(name="Happy Bones", link="https://goo.gl/maps/aGH65UrSV8g7Cgxw5", specialty="Cappuccino")
    Recommendation.objects.create(name="Bluestone Lane", link="https://g.page/Bluestone-Lane-Spring-St-Nolita?share", specialty="Avo Smash")
    Recommendation.objects.create(name="Blue Bottle Coffee", link="https://goo.gl/maps/epJr5sA3e7dYTj6C9", specialty="Flat White")
    Recommendation.objects.create(name="Lafayette", link="https://goo.gl/maps/K9Eqchu8i7icHm5y9", specialty="Macarons")
    Recommendation.objects.create(name="Café Grumpy", link="https://goo.gl/maps/VTVQqU3daj5xyhFp8", specialty="Cold Brew")
    Recommendation.objects.create(name="Cha Cha Matcha", link="https://goo.gl/maps/RkUtBXdsKXBEsmac7", specialty="Matcha, of course!")


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0011_auto_20190815_1408'),
    ]

    operations = [
        migrations.RunPython(
            unassign_all_investors_from_representatives,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        )
    ]

