# Generated by Django 2.2.4 on 2019-08-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0012_auto_20190815_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='coffee_per_day',
            new_name='coffee_count',
        ),
    ]
