SEARCHING_FOR_COFFEE_BUDDY = "I'm searching for your coffee buddy. :coffee: Let me know if you change your mind. :wink:"
HANG_IN_THERE = "Hang in there. :muscle: I'm still looking for your buddy!"
COFFEE_REQUEST = "Need a little stretch? :ok_woman: Let's grab a coffee?"
COULD_NOT_FIND_MATCH = "I'm sorry, I couldn't find a buddy. :disappointed: Let's try again later."
LETTING_YOUR_BUDDY_KNOW = "Hang tight, letting your buddy know!"
SUCCESS_MESSAGE = "Woo hoo! Go get your brew!"
MAYBE_NEXT_TIME = "Oh snap! Maybe next time. :shrug:"
NO_MATCHES_FOUND = "No matches found!"
NO_REPLY = "Nah..."
RAN_OUT_OF_TIME = "Looks like you ran out of time. :disappointed: If you want me to find you another buddy, let me know!"

JOINING_MESSAGE = "Hey there! :wave: Thanks for joining! Let's get some things nailed down:"
SET_PREFERENCES = ":coffee: Set Coffee Preferences"
PREFERENCES_RECEIVED = "Your preferences are all set! Use */coffee* to find your first buddy. :coffee:"

